### PR TITLE
Added more debugging information

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
## Purpose

This adds more debugging information especially when calling shell commands as described in issue #562.

### CODE REVIEW

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, looks good to me:

image

I created a PR that I believe would fix the problems you see here: #579 🤞

**Review by abravalheri — APPROVED** [review]

**Comment by FlorianWilhelm** [comment]
@abravalheri, I think using `logger.report` looks a bit more consistent for checks and verifications:
image

**Comment by FlorianWilhelm** [comment]
> Thank you very much @FlorianWilhelm , it does look great!
> 
> I suppose the next step would be also using `record` for that extra spourious line right (the one starting with `last command`)?
> 
> After we merge this PR, I can try to give it a try.

Hm... right. I wasn't sure which `action` to pick as we are only returning the output of the command. Do you have a suggestion?

**Comment by abravalheri** [comment]
"output" seems good to me, or just "failed"...

**Comment by FlorianWilhelm** [comment]
@abravalheri, I opted now for `info`. What do you think?
image

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm . It looks very good!

Please feel free to merge ;)

**Pull request merged**
