### PR TITLE
issue #605 added support to force line endings to LF for text files

### PR DESCRIPTION
**Pull request by julie777**
also fixed the one file with the wrong line endings

## Purpose
_Describe the problem or feature in addition to a **link to the issues**._

## Approach
_How does this change address the problem?_

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Resources & Links

_Links to blog posts, patterns, libraries or addons used to solve this problem_

### CODE REVIEW

**Comment by julie777** [comment]
added another commit for a missed file change. These can be squashed when merged.

**Comment by julie777** [comment]
This is my first time going through this specific process. I'm not sure how to squash my commits into a single commit or if that happens during the merge of the pull request.

**Comment by abravalheri** [comment]
Hi @julie777, thank you very much for looking into this. And congratulations for your first PR!

(Sorry, I still haven't had the time to reply to your other messages/comments/issues, but I promise I will get to that soon!)

Can you elaborate a bit more why the current solution (`args: ['--fix=lf']` in `.pre-commit-config.yml`) does not work?

(I am disregarding the situations when PyScaffold devs forget to run `pre-commit` install. In those situations isn't it a good thing to have some discrepancies so it serves as reminder to do the installation?)

**Comment by julie777** [comment]
> Can you elaborate a bit more why the current solution (args: ['--fix=lf'] in .pre-commit-config.yml) does not work? (Or at least in which situations it would not work).

Mostly because it is built in to git and doesn't require and hooks that might not get run or not run until CI. 
I think the doc I linked might have a more detailed explanation.

**Comment by FlorianWilhelm** [comment]
Thanks for this PR @julie777. This PR introduces `.editorconfig` and I wonder if we should also add more things like
```
[*.py]
indent_style = space
indent_size = 4
```
and if maybe later it should also be part of the PyScaffold template?

The fix for the line endings in the SVG graphic is fine. Regarding the `.gitattributes` I am also not 100% as I am actually not using them so often. I found this [Stackoverflow question](https://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes-file) and at least here the recommendation is not to use it as Git might make a mistake and convert non-text files. Then there is [this question](https://stackoverflow.com/questions/33872793/git-text-auto-in-the-gitattributes-file-and-line-endings?noredirect=1&lq=1) from a Windows users confused about the effects of Git's automatic conversion from the repo to the working directory. I am just not sure if adding this really helps. Shouldn't it be enough to have it in `.editorconfig` and `pre-commit`?

**Pull request closed without merging**
