### PR TITLE
Add conda to docs

### PR DESCRIPTION
**Pull request by abravalheri**
This PR is related to the discussion on #135

### CODE REVIEW

**Review by FlorianWilhelm — APPROVED** [review]
Really good introduction I think.

**Comment by abravalheri** [comment]
First I thought about adding some comment on the FAQ (which is usually what I do when I don't have time/brain to compose a proper text explaining things), but then it kind of evolved... Moreover `conda` is important enough to have its own section...

The rendered version can be seen at [readthedocs](https://pyscaffold.org/en/latest/conda.html)

Thank you for the review @FlorianWilhelm

**Comment by maresb** [comment]
This is a really nice writeup. I'm very impressed.

A potential problem I see is that "Creating Conda Packages" is a very niche topic which 99% of users will probably never do. But using `conda` in conjunction with PyScaffold in particular `dsproject` is a very important mainstream theme. This niche topic is now very prominent in the PyScaffold documentation, while (as far as I can tell) there isn't really a prominent explanation of using `conda` in general. I think this gives the wrong impression about what `conda` is mainly for. I wonder if it would be better to: 

* rename the topic "Creating Conda Packages" → "Using Conda Packages",
* describe using `conda` as a package manager, the `environment.yml` file, etc, and
* put this section which you just wrote at the end.

**Comment by abravalheri** [comment]
Thank you very much for the feedback @maresb, I really like the suggestions.
I will open a new issue so we can track the progress in this area.

Hopefully we can re-use some of Florian's previous explanations in #368 and #426 to compose the extra sections.

**Pull request merged**
