### PR TITLE
Rework get_template to be used in extensions

### LINKED ISSUE #252: Rework get_template to be used in extensions
Provide a version of `get_template` that can be used in extensions to avoid code duplication.

### PR DESCRIPTION
**Pull request by abravalheri**
This commit closes #252

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
This looks great, thanks @abravalheri! Regarding the failed PY3.5 check. Should we pin `pipx` to a version that runs with PY3.5? At least for a PyScaffold version 3.3. With version 4.0 we will drop the PY3.5 support.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I think that is sensible, otherwise it will break all the builds in the CI.
It is a pity `pipx` moved away from Python 3.5 before 2020-09-13. There are a few important distributions that I guess will rely on 3.5 up to that date (some Ubuntu LTS for example).

**Comment by abravalheri** [comment]
And we see ourselves again in the middle of a Dependency Hell 😝 

Apparently `pipx==01.0` solves 3.5 but breaks other tasks.

**Comment by FlorianWilhelm** [comment]
Hi, is there anyone still working on this?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm regarding the `get_template` itself, I think this PR solves the issue.
However the CI is complicated... and I don't have many ideas on how to start solving it.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I managed to make the tests start running again on windows and osx.
I believe the best would be merge this change (since the tests show the changed function works even for windows).
If there is another problem with the CI, the best would be try to address them in a separated issue.

**Comment by FlorianWilhelm** [comment]
Thanks a lot @abravalheri!

**Pull request merged**
