### PR TITLE
Larger reorg and simplification of the sidebar

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
## Purpose
From what I hear some users have trouble with PyScaffold's current documentation structure. This is an attempt and suggestion on how to simplify the organization of the docs.

### CODE REVIEW

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, I like the reorganisation, specially the new usage section... It makes a lot of sense to me.

I was wondering, what if instead of putting advanced topics in the FAQ, we actually have an "Advanced" section and then use a toctree to actually include the advanced topics there?

**Comment by FlorianWilhelm** [comment]
Thanks, @abravalheri, that's a good idea! Let me try something...

**Review by abravalheri — APPROVED** [review]
I really like it 😄 

Thank you @FlorianWilhelm

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri :-)

**Pull request merged**
